repos:
-   repo: https://github.com/pycqa/isort
    rev: '5.8.0'  # Use the revision sha / tag you want to point at
    hooks:
    - id: isort
      exclude: ^tests/
-   repo: https://github.com/psf/black
    rev: '21.8b0'
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    - id: mypy
      exclude: ^tests/|docs
