# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: flake8
        files: 'src/superintendent/.*\.py'
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        files: 'src/superintendent/.*\.py'
