# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: superintendent
      POSTGRES_PASSWORD: superintendent
      POSTGRES_DB: labelling
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  notebook:
    image: voila
    restart: always
    volumes:
      - ./voila-interface.ipynb:/home/anaconda/app/app.ipynb
    ports:
      - 8866:8866

  orchestrator:
    image: voila
    restart: always
    entrypoint: /opt/conda/bin/python orchestrate.py
    volumes:
      - ./orchestrate.py:/home/anaconda/app/orchestrate.py
