name: Package build and publishing

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      FLIT_USERNAME: __token__
      FLIT_PASSWORD: ${{ secrets.pypi_secret }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -qq --upgrade pip flit testver
    - name: Set testing variables
      if: "!startsWith(github.event.ref, 'refs/tags')"
      run: |
        testver src/superintendent/
        echo "::set-env name=FLIT_INDEX_URL::https://test.pypi.org/legacy/"
        echo "::set-env name=FLIT_PASSWORD::${{ secrets.test_pypi_secret }}"
    - name: Build
      run: flit build
    - name: Publish
      run: flit publish
